name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t information-system-fe .    
        
      - name: Tag Docker image
        run: docker tag information-system-fe trongvinhttd/information-system-fe:latest

      - name: Push Docker image
        run: docker push trongvinhttd/information-system-fe:latest
